@host=https://kangmin.shop/api/
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVGVzdCIsImlzcyI6ImthbmdtaW4uc2hvcCIsIl9wayI6NSwiZXhwIjoxNTk4NjAyNzUwfQ.OZHvoPis4aubxRxA8BkvdBksURmddXLbwwk948kmOMw

GET {{host}}mainList HTTP/1.1
token: {{token}}


###

POST {{host}}gojiList HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "code": 1,
  "clCode": 0,
  "orderType": 0,
  "keyword": "",
}


###

POST {{host}}insertBattle HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "baSubject":"ㅈㄷㄱㅈㄷㄱ",
  "baPwd":"",
  "bcCode":1,
  "bzCode":1,
  "btCode":1,
  "blCode":2,
  "baDate":"2020-08-11",
  "baContent":"",
  "teamA":
    {"name":"","member":[5]},
  "teamB":
    {"name":"","member":[]}
}