@fcm=https://fcm.googleapis.com/fcm/send
@host=https://kangmin.shop/api/
@tokenFb=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoi6rmA6rec7IudZmIiLCJpc3MiOiJrYW5nbWluLnNob3AiLCJfcGsiOjQxLCJleHAiOjE2MDcxMzI3Mjh9.wYO8KC3F5L8WNZuGZ0Iu7GdqgZBo_OEn1j3lqc73O_Y
@tokenKakao=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoi6rmA6rec7IudIiwiaXNzIjoia2FuZ21pbi5zaG9wIiwiX3BrIjoyMSwiZXhwIjoxNjA2MDEwMjk0fQ.fs8nwQh0gVTQqaK4E82TUk-V79jXLwFYzhXwcyertvQ
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoi6rmA6rec7IudIiwiaXNzIjoia2FuZ21pbi5zaG9wIiwiX3BrIjoyMSwiZXhwIjoxNjA3NjU1MTY3fQ.8DWfTM0rpWDvmjEB0PCBSF5shKVNcaPO0ghPgOlYofw
@pushKeyKakao=d9P80U8JTPKd8o6OCNbIt4:APA91bENEKBovx8G4mn3aKu9jnIe_xBJVh1_xqLLrUfs3IDCEKyx4UaatPpltqZmCPsRbVSbc-ga8jWJ8PytoNueL0aFndn-s6EKRoVKPWw4S059zc3CsFiTseqcxXMqkDCj-mkQciYx
@pushKey=fITkvNxP80Yon4znlXr-cF:APA91bEb5A-_YB7-pZ1cVjDXfoCCYx8aIalX8yVjgpFJHy7_hA0DUoV-yCSZJ9UZ87QxnqxYUNT65H0nWwLBykEoGn-3q8YQ9Gl65XE3wDgeHPXqD7aoxaKiLvahBUF5krMqT7EusvuP

GET {{host}}mainList HTTP/1.1
token: {{token}}


###

POST {{host}}gojiList HTTP/1.1
Content-Type: application/json
token: {{tokenKakao}}

{
  "code": 1,
  "clCode": 0,
  "orderType": 3,
  "keyword": "",
  "lat": 37.5683394,
  "lon": 126.9511045
}


###

POST {{host}}insertBattle HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "baSubject":"ㅈㄷㄱㅈㄷㄱ",
  "baPwd":"",
  "bcCode":1,
  "bzCode":1,
  "btCode":1,
  "blCode":2,
  "baDate":"2020-08-11",
  "baContent":"",
  "teamA":
    {"name":"","member":[5]},
  "teamB":
    {"name":"","member":[]}
}

###

POST {{host}}updateBattle HTTP/1.1
Content-Type: application/json
token: {{token}}

{
}

###

POST {{host}}resultBattle HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "baPk": 106,
  "teamA": {
    "gameResult": 1,
    "timeScope": "5.0",
    "playScope": "5.0",
    "lat": "33.2539385",
    "lon": "126.5595922"
  },
  "teamB": {
    "gameResult": 0,
    "timeScope": "",
    "playScope": "",
    "lat": "33.2539385",
    "lon": "126.5595922"
  }
}

###

POST {{host}}locker HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "pageNum": 1
}

###

POST {{host}}updateBattlePk HTTP/1.1
Content-Type: application/json
token: {{tokenKakao}}

{
  "baPk": 0
}

###

DELETE {{host}}locker/186 HTTP/1.1
Content-Type: application/json
token: {{token}}

###

GET {{host}}getPush/{{pushKeyKakao}} HTTP/1.1
Content-Type: application/json
token: {{{{tokenKakao}}}}

{
  "userPushKey" : {{pushKeyKakao}}
}

### recomMap 추천운동시설 리스트

GET {{host}}getBattleEtc HTTP/1.1
Content-Type: application/json
token: {{tokenFb}}

{
}


####
POST {{fcm}}
Authorization: key=AAAABOeF95E:APA91bGCKfJwCOUeYC8QypsS7yCAtR8ZOZf_rAj1iRK_OvIB3mYXYnva4DAY28XmUZA1GpXsdp1eRf9rPeuIedr7eX_7yFWbL-C_4JfVGSFGorCdzjOA0AyYPxB83M8TTAfUj62tUZhH
Content-Type: application/json

{
  //"to": "d7hOVG1F9UNWkoxTcatfvd:APA91bHplPpNYfDNEyXfU2xuE24Pbi2YK4EzaRp4DPbL7XQW7PdEKdYDuW3XQu1p-5wJHc3Bcf8Z4a5wj5Gv5Z7_uC2XbX8AQk-tZsEhj7IuyD86APuGIJpDI_XlqgZWr9RnqTeeglp9",
  "to": "cDNp8zs7T4amhKsghPk45m:APA91bGd1VEzl6qb4UD0SRnlml-j-EPxlyVdY_R6ElhN9eOHQgowfGtcjwPVd_eG9W6c6jQ1VI8az5omiVkSgaeiLiYEubDKJp6KedDRUFeW6Kao_dcPiRCTkAy0fN3F_fgQXfpovUsW",
  "notification": {
    //"title": "title",
    //"body": "body",
    //"image": "https://lespo.s3.ap-northeast-2.amazonaws.com/stroage/img-user2.png"
  },
  "data": {
    "baPk": "192", 
    "body": "Qqq", 
    "imgUrl": "https://lespo.s3.ap-northeast-2.amazonaws.com/stroage/img-user2.png", 
    "screen": "battlechat", 
    "tabIndex": "1", 
    "title": "김규식"
  }
}