@fcm=https://fcm.googleapis.com/fcm/send
@host=https://jejubattle.com/api/
@tokenFb=cDNp8zs7T4amhKsghPk45m:APA91bEB7JZIk2PFHLpoWoQF-uOmtm2cVRQKkYV9WxUz0AmsSKUbjI5JhQTXgwL03LRrV3q7LjvbVFHVCP3z_4xgEJ6OEAc-GXSl-07iT4SKgCoUAgN7EMK8zdbU7TB0hAURerRrZNTH
@tokenKakao=f_jnWwZwdUOCtkVZrvJWKT:APA91bH2DhUVxxPwbbnM3jtnoxbej9ZGgJJXJ7HG1eS9aoqXCdcg9qhf0VBHNS9gpjRzUSqeLmruftjisgfHoMqWjsRUjYY5vjE6_u9RtqY9AYlpCoL7UFShapFPiCc7gdg-mJJFVzwZ
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoi6rmA6rec7IudIiwiaXNzIjoia2FuZ21pbi5zaG9wIiwiX3BrIjoyMSwiZXhwIjoxNjA5NDY3NzUwfQ.qcSt_Arq9B3sb6IHaUb_D65aZ5ledSRz3QElzC0evIM
@pushKeyKakao=d9P80U8JTPKd8o6OCNbIt4:APA91bENEKBovx8G4mn3aKu9jnIe_xBJVh1_xqLLrUfs3IDCEKyx4UaatPpltqZmCPsRbVSbc-ga8jWJ8PytoNueL0aFndn-s6EKRoVKPWw4S059zc3CsFiTseqcxXMqkDCj-mkQciYx
@pushKey=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVy5kZXYiLCJpc3MiOiJrYW5nbWluLnNob3AiLCJfcGsiOjQ1MiwiZXhwIjoxNjIwNDM3MzI4fQ.2meq6JGxKlqPAoQZuUrqvciVZFHFdRMg6zbIArwxK3s

GET {{host}}mainList HTTP/1.1
token: {{token}}

###

POST {{host}}snsSignin HTTP/1.1
Content-Type: application/json
token: {{tokenFb}}

{
    "userId": "3271555769600856",
   "userCode": 4,
   "userPushkey": "",
    "deviceOs" : 1,
    "deviceOsVer" : "29"
}

###

POST {{host}}gojiList HTTP/1.1
Content-Type: application/json
token: {{tokenKakao}}

{
  "code": 1,
  "clCode": 0,
  "orderType": 3,
  "keyword": "",
  "lat": 37.5683394,
  "lon": 126.9511045
}


###

POST {{host}}insertBattle HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "baSubject":"ㅈㄷㄱㅈㄷㄱ",
  "baPwd":"",
  "bcCode":1,
  "bzCode":1,
  "btCode":1,
  "blCode":2,
  "baDate":"2020-08-11",
  "baContent":"",
  "teamA":
    {"name":"","member":[5]},
  "teamB":
    {"name":"","member":[]}
}

###

POST {{host}}updateBattle HTTP/1.1
Content-Type: application/json
token: {{token}}

{
}

###

POST {{host}}resultBattle HTTP/1.1
Content-Type: application/json
token: {{token}}

{
  "baPk": 106,
  "teamA": {
    "gameResult": 1,
    "timeScope": "5.0",
    "playScope": "5.0",
    "lat": "33.2539385",
    "lon": "126.5595922"
  },
  "teamB": {
    "gameResult": 0,
    "timeScope": "",
    "playScope": "",
    "lat": "33.2539385",
    "lon": "126.5595922"
  }
}

###

POST {{host}}wishList HTTP/1.1
Content-Type: application/json
token: {{tokenKakao}}

{
  "pageNum" : 1
}

###

POST {{host}}updateBattlePk HTTP/1.1
Content-Type: application/json
token: {{tokenKakao}}

{
  "baPk": 0
}

###

DELETE {{host}}locker/186 HTTP/1.1
Content-Type: application/json
token: {{token}}

###

GET {{host}}getPush/{{pushKeyKakao}} HTTP/1.1
Content-Type: application/json
token: {{{{tokenKakao}}}}

{
  "userPushKey" : {{pushKeyKakao}}
}

### recomMap 추천운동시설 리스트

GET {{host}}getBattleEtc HTTP/1.1
Content-Type: application/json
token: {{tokenFb}}

{
}

### battle 목록
POST {{host}}battle HTTP/1.1
Content-Type: application/json
token: {{tokenKakao}}

{
        "boCode": 1,
        "lat": 37.55375859999999,
        "lon": 126.9809696,
        "baCode": 1,
        "bmCode": 1,
        "blCode": 1,
        "bpCode": 1,
        "caCode": [{
                        "code": 1
                },
                {
                        "code": 4
                }
        ],
        "pageNum": 2
}

### popup
GET {{host}}popup HTTP/1.1
Content-Type: application/json
token: {{tokenKakao}}

{

}

####
POST {{fcm}}
Authorization: key=AAAABOeF95E:APA91bGCKfJwCOUeYC8QypsS7yCAtR8ZOZf_rAj1iRK_OvIB3mYXYnva4DAY28XmUZA1GpXsdp1eRf9rPeuIedr7eX_7yFWbL-C_4JfVGSFGorCdzjOA0AyYPxB83M8TTAfUj62tUZhH
Content-Type: application/json
token: {{pushKeyKakao}}

{
  //"to": "cSU1jr8rQGSM4JEBlsWY1f:APA91bETzqnC8mOLap0aEAQmKpuBEwUutL6pPKoah0qXmxM-ij-8dwa5LbDQl7EiXvOmJafBtcJea6_jVDltTm8Bkj3brebM-Aaia5VsrBSOqG11BK0tVTF5I33ixnTAlpModYYDEtTg",
  //"to": "fVqmUzGEQ3aZTmvz8zhAmL:APA91bFOxzaqgqWtb4y3u7hCCINayV7BK0gkPhbjrYYC389AifmFQoYnfZvMMZtMIvQuR5cIOtJPZc_DDl4QRfEwB-uNAQsRPLG8XxqV43BvQGEG99AGLPN6yLRBAa5V1C9w3Ug2qOSO",
  "to": "f_jnWwZwdUOCtkVZrvJWKT:APA91bH2DhUVxxPwbbnM3jtnoxbej9ZGgJJXJ7HG1eS9aoqXCdcg9qhf0VBHNS9gpjRzUSqeLmruftjisgfHoMqWjsRUjYY5vjE6_u9RtqY9AYlpCoL7UFShapFPiCc7gdg-mJJFVzwZ",
  
  "notification": {
     "title": "noti-title",
     "body": "noti-body"
     //"image": "123"
     //"imageUrl": "https://lespo.s3.ap-northeast-2.amazonaws.com/stroage/img-user2.png"
  },
  "priority" : "high",
  "data": {
    "baPk": "1060", 
    "body": "data-dody", 
    "imgUrl": "https://lespo.s3.ap-northeast-2.amazonaws.com/stroage/img-user2.png", 
    "screen": "admin", 
    // "tabIndex": "2", 
    "title": "data-title"
  }
}