-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdeHrsThydYyVKMw+
ZKhXVKhD4QQttzaX6FAkzDB1NSmgCgYIKoZIzj0DAQehRANCAAT/bxFshUoJ4gna
9kzGtXT3xYW5TgW8z1j5o41s1aZQqL5utGZJu4/FZiEugeRA8zKWBCdbAsa34PaJ
MmbKsVo2
-----END PRIVATE KEY-----